### ISSUE TITLE
Detection of circular dependencies

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-requirements#16]
In the current [ISO 19115-3](https://github.com/metanorma/iso-19115-3/) there are multiple circular dependencies, which means that implementation of them cannot be possible.

This means that we need to detect these circular loops and alert the authors to think hard and break them.

**Comment by ronaldtse** [comment]
Example in conformance tests:

`sources/ed2/sections/tables/yaml/19115-1-xml-cc.yaml`:
```yaml
  - name: Validation of XML instance for metadata basic information
    identifier: https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/basic
    target: https://standards.isotc211.org/19115/-1/1/req/metadata-xml/basic
    dependencies:
    - https://standards.isotc211.org/19115/-1/1/conf/metadata-minimal-xml
    - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/common
    - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/multilingual
```

`sources/ed2/sections/tables/yaml/19115-xml-min-cc.yaml`:
```yaml
  - name: Validation of minimum valid XML metadata instance
    title: Minimum valid XML metadata instance
    identifier: https://standards.isotc211.org/19115/-1/1/conf/metadata-minimal-xml
    target: https://standards.isotc211.org/19115/-1/1/req/metadata-minimal-xml
    subject: Metadata instance
    tests:
    - name: Valid minimum metadata instance
      identifier: https://standards.isotc211.org/19115/-1/1/conf/metadata-minimal-xml/valid
      targets:
      - https://standards.isotc211.org/19115/-1/1/req/metadata-minimal-xml/valid
      purpose: Verify that the minimal XML metadata instance document is well formed and valid
      method: Use an XML validation tool to determine if XML instance is valid using the XML schema `mdb.xsd`. See discussion of validation tools in <<scl_no_systematic_test>>.
      type: Validation
      dependencies:
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/basic
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/citation
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/common
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/extent
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/identification
      - https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/multilingual
```

There's a very clear circular dependency here where:
* `https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/basic` depends on
* `https://standards.isotc211.org/19115/-1/1/conf/metadata-minimal-xml` and vice versa

One of these must drop the other because this loop does not make sense.
